### ISSUE TITLE
Issues with capitalizing "Mac"

### ISSUE THREAD

**Issue by JinBean** [infiton/capitalize-names#10]
Names like Macie/Macy or Mackenzie become MacIe/MacY and MacKenzie

**Comment by infiton** [comment]
Thank you for flagging this issue and apologies for the huge delay in addressing it (I've just recently had some time to do some work like this). The library has been extended in version `1.2.0` to allow for more control over formatting rules. By default now the library will only capitalize `Macie` to `MacIe` if it thinks it's a last name or you explicitly tell it to treat it that way. Here are some examples:

```ruby
CapitalizeNames.capitalize("macie bean") # => "Macie Bean"
CapitalizeNames.capitalize("macie") # => "MacIe"
CapitalizeNames.capitalize("macie", format: :givenname) # => "Macie"
CapitalizeNames.capitalize("macie", skip_mac: true) # => "Macie"
```
